global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    environment: local
    platform: tour-platform

rule_files:
  - /etc/prometheus/alerts.yml

scrape_configs:
  - job_name: otel-collector-internal
    static_configs:
      - targets: ["otel-collector:8888"]

  - job_name: application-otel-metrics
    static_configs:
      - targets: ["otel-collector:8889"]
